### ISSUE TITLE
ImportError: cannot import name 'slow_r50_detection' from 'pytorchvideo.models.hub

### ISSUE THREAD

**Issue by TianhaoFu** [facebookresearch/pytorchvideo#70]
## 🐛 Bugs / Unexpected behaviors

when using
```
model_name = "slowfast_r50"
SLOWFAST50_MODEL = torch.hub.load("facebookresearch/pytorchvideo", model=model_name, pretrained=True)
```
I came across bug follows
```
/root/.cache/torch/hub/facebookresearch_pytorchvideo_master/hubconf.py in <module>()
      2 
      3 dependencies = ["torch"]
----> 4 from pytorchvideo.models.hub import (  # noqa: F401, E402
      5     efficient_x3d_s,
      6     efficient_x3d_xs,
ImportError: cannot import name 'slow_r50_detection' from 'pytorchvideo.models.hub' (/usr/local/lib/python3.7/dist-packages/pytorchvideo/models/hub/__init__.py)
```

## Instructions To Reproduce the Issue:

1. My code came from [https://pytorchvideo.org/docs/tutorial_torchhub_inference](https://pytorchvideo.org/docs/tutorial_torchhub_inference).

2. My environment is google colab.
----------------
It Seems is a bug from official respository. Thanks

**Comment by Meryl-Fang** [comment]
Second it, just met the same problem! (For now I just comment out the models that raise error :/ )

**Comment by kalyanvasudev** [comment]
@TianhaoFu , @Meryl-Fang , could please provide more details on how you installed pytorchvideo and your testing environment? 

When I ran the following notebook in Colab, I did not have issues - https://colab.research.google.com/github/facebookresearch/pytorchvideo/blob/master/tutorials/torchhub_inference_tutorial.ipynb

**Comment by Kupchanski** [comment]
Same. 
I just copy code from https://pytorchvideo.org/docs/tutorial_torchhub_inference cell by cell and got this error on model import from torch.hub

**Comment by kalyanvasudev** [comment]
Got it, I was able to pinpoint it down. Looks like the pip build is out of date. I will update it today. 

Alternatively, running `!pip install "git+https://github.com/facebookresearch/pytorchvideo.git"` should fix the problem temporarily.

**Comment by kaitsmith22** [comment]
Even though I reinstalled Pytorchvideo using `pip install "git+https://github.com/facebookresearch/pytorchvideo.git"` I am still encountering the same problem. My environment is a Jupytr notebook.

**Comment by taliegemen** [comment]
The error still persists on my local machine even if i install from git. There is no problem on google colab though.

**Comment by kalyanvasudev** [comment]
Hi, I've updated the pip builds too to match the latest commits. All the installation methods  mentioned [here](https://github.com/facebookresearch/pytorchvideo/blob/master/INSTALL.md) should work now. I just verified it. 

Please let me know if the issue persists!

**Comment by kalyanvasudev** [comment]
Closing the issue since it has been resolved. But feel free to open it again if the problem still persists for you.

For all of you who installed version 0.1.1, I'd recommend uninstalling it and installing 0.1.2 or higher. Thanks!
